services:
  certbot:
    image: bybatkhuu/certbot:3.0.1-250526
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
      - CERTBOT_DNS_TIMEOUT=${CERTBOT_DNS_TIMEOUT:-30}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/storage/nginx/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge"
      - "./volumes/storage/nginx/ssl:/etc/letsencrypt"
    network_mode: host
    tty: true

  nginx:
    image: bybatkhuu/nginx:3.0.3-250526
    depends_on:
      - certbot
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/storage/nginx/logs:/var/log/nginx"
      - "./volumes/storage/nginx/www:/var/www"
      - "./volumes/storage/nginx/ssl:/etc/nginx/ssl"
      - "./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/sites-enabled"
      - "./volumes/storage/nginx/configs/templates:/etc/nginx/templates"
    network_mode: host
    tty: true
    command: ["--https=lets"]
